---
title: "Groundhog exploration"
author: "Tamás Nagy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)

theme_set(theme_light())

```

# Reading the data

```{r}
groundhogs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/groundhogs.csv')
predictions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-30/predictions.csv')

```

## How many groundhogs in each region

```{r}

groundhogs |> 
    ggplot() +
    aes(y = region) +
    geom_bar() +
    labs(y = NULL)

groundhogs |> 
    count(region) |> 
    mutate(region = fct_reorder(region, n)) |> 
    ggplot() +
    aes(y = region, x = n) +
    geom_col() +
    labs(y = NULL)


```

```{r}
groundhogs |> count(country)

```

Create a new dataset where groundhogs are joined to predictions

```{r}

gh_pred <- 
    groundhogs |> 
    left_join(predictions, by = "id")


shadow_pred <- 
    gh_pred |> 
    group_by(id) |> 
    summarise(prop_shadow = mean(shadow, na.rm = TRUE))

gh_pred |> 
    group_by(id, shortname) |> 
    summarise(start = min(year)) |> 
    mutate( name = paste0(id, "_", shortname), 
            name = fct_reorder(name, start)) |> 
    ggplot() +
    aes(y = name) +
    geom_point(aes(x = start))

```

## Groundhog active time

```{r}
gh_pred |> 
    group_by(id, shortname) |> 
    summarise(start = min(year),
              end = max(year)) |> 
    ggplot() +
    aes(y = id, yend = id, x = start, xend = end) +
    geom_segment()
```


```{r}

usa_map <- map_data("state")

usa_gh <- 
    groundhogs |> 
    filter(country == "USA") |> 
    left_join(shadow_pred, by = "id")


usa_map |> 
    ggplot(aes(x = long, y = lat)) +
    geom_polygon(aes(group = group), fill = "lightgrey", color = "darkgray") +
    coord_map() +
    geom_point(data = usa_gh, 
               aes(x = longitude, y = latitude, size = predictions_count, alpha = predictions_count),
               color = "red") +
    labs(x = NULL, y = NULL, size = "# of predictions", alpha = "# of predictions",
         title = "USA groundog sites")


```



```{r}

usa_map |> 
    ggplot(aes(x = long, y = lat)) +
    geom_polygon(aes(group = group), fill = "lightgrey", color = "darkgray") +
    coord_map() +
    geom_point(data = usa_gh, 
               aes(x = longitude, y = latitude, size = predictions_count, color = prop_shadow),
               alpha = .6) +
    scale_color_viridis_c() +
    labs(x = NULL, y = NULL, size = "# of predictions", color = "Prop of shadows",
         title = "USA groundog sites and proportion of shadows")
    
    
```




